[project]
name = "ml-actions-benchmarking"
version = "0.1.0"
requires-python = "~=3.11"

dependencies = [
    "protovalidate == 1.0.0",
    "tensorflow",
    "numpy",
    "tensorboard",
    "tensorboardx",
    "google-cloud-pubsub",
]

[project.optional-dependencies]
test = [
    "pytest"
]
