# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow is an end-to-end integration test for the
# run-benchmarks.yaml reusable workflow.
name: Benchmark workflow e2e test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'benchmarking/**'
      - '.github/workflows/run-benchmarks-e2e-test.yaml'
      - '.github/workflows/run-benchmarks.yaml'
  workflow_dispatch:

permissions:
  contents: read

# Cancel any previous runs on the same branch when a new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run_e2e_test:
    name: Benchmarking workflow e2e test
    uses: ./.github/workflows/run-benchmarks.yaml
    with:
      registry_file: "benchmarking/e2e_test/test_registry.pbtxt"
      workflow_type: "PRESUBMIT"
      publish_metrics: false
      pub_sub_gcp_project_id: "ml-oss-benchmarking-testing"
      pub_sub_gcp_topic_id: "public-results-dev"
