# A workflow to test waiting for remote connections to the runner.
name: Connection Test with the Bash-based fallback
# This is a copy of the wait-for-connection-test.yaml, but with a Python-less container.
on:
  pull_request:
    paths:
    - ci_connection
    - .github/workflows/wait-for-connection-bash-fallback-test.yaml
    branches:
      - main
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        required: true
        default: 'no'
        options:
        - 'yes'
        - 'no'
defaults:
  run:
    shell: bash
# Cancel any previous iterations if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  wait-test:
    strategy:
      fail-fast: false
      matrix:
        runner: ["linux-x86-n2-16"]
        instances: ["1"]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    container:
      # image: us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/ml-build@sha256:cec01011e627c0fd101c521a8af7c09ce4557ab6dcc9f8678aeb67a3182ed821 # ratchet:tensorflow/ml-build:latest
      image: index.docker.io/library/ubuntu@sha256:6d8d9799fe6ab3221965efac00b4c34a2bcc102c086a58dff9e19a08b913c7ef # ratchet:ubuntu:20.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Echo
        run: |
          set -x
          echo "Real job here..."
      # Halt for connection if workflow dispatch is told to or if it is a retry with the label halt_on_retry
      - name: Wait For Connection
        uses: ./ci_connection/
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
