# A workflow to test waiting for remote connections to the runner.
name: Connection Test without pre-installed Python
# This is a copy of the wait-for-connection-test.yaml,
# but with a Python-less container.
# The connection step should seamlessly find, or install, and use a suitable one.
on:
  pull_request:
    paths:
    - ci_connection
    - .github/workflows/wait-for-connection-no-python.yaml
    branches:
      - main
permissions: {}
defaults:
  run:
    shell: bash
# Cancel any previous iterations if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  wait-test:
    strategy:
      fail-fast: false
      matrix:
        runner: ["linux-x86-n2-16", "windows-x86-n2-16"]
        instances: ["1"]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    container:
      image: ${{ startsWith(matrix.runner, 'linux') && 'us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/ml-build@sha256:cec01011e627c0fd101c521a8af7c09ce4557ab6dcc9f8678aeb67a3182ed821' || (startsWith(matrix.runner, 'windows') && null) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - name: Echo
        run: echo "Real job here..."

      # Halt for connection if workflow dispatch is told to or if it is a retry with the label halt_on_retry
      - name: Wait For Connection
        uses: ./ci_connection/
        env:
          # Hide any Python present under python/python3 for full execution of the
          # Python finding part of wait_for_connection.sh
          MLCI_HIDE_PYTHON: 1
          # Allow installing Python, and the packages necessary to install
          # it e.g., uv, curl, unzip
          MLCI_ALLOW_PYTHON_INSTALL: 1
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
